spring.application.name=PedroDiaz
server.port=9000
spring.datasource.url=jdbc:h2:file:./db/basedatos/testdb
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show_sql=true
spring.h2.console.enabled=true
spring.thymeleaf.cache=true

