
DELETE FROM estadisticas;
DELETE FROM futbolista;
DELETE FROM equipo;

-- Equipos: 1=Real Betis Balompié (primer equipo), 2=Betis Deportivo (Real Betis B), 3=Real Betis Féminas
INSERT INTO equipo (id, nombre, categoria, img_equipo) VALUES (1, 'Real Betis Balompié', 'Primera División', '/img/equipos/betis.png');
INSERT INTO equipo (id, nombre, categoria, img_equipo) VALUES (2, 'Betis Deportivo', 'Segunda RFEF / Segunda Federación', '/img/equipos/betis_deportivo.png');
INSERT INTO equipo (id, nombre, categoria, img_equipo) VALUES (3, 'Real Betis Féminas', 'Liga F', '/img/equipos/betis_fem.png');

-- Futbolistas (Real Betis primer equipo) (IDs 101-130)
INSERT INTO futbolista (id, nombre, apellidos, img_futbolista, fecha_nacimiento, fecha_inicio_contrato, nacionalidad, num_camiseta, salario_mensual_base, equipo_id, tipo) VALUES (101, 'Rui', 'Silva', '/img/futbolistas/rui_silva.png', '1994-02-07', '2021-07-01', 'Portugal', 13, 180000, 1, 'PORTERO');
INSERT INTO futbolista (id, nombre, apellidos, img_futbolista, fecha_nacimiento, fecha_inicio_contrato, nacionalidad, num_camiseta, salario_mensual_base, equipo_id, tipo) VALUES (102, 'Isco', 'Alarcón', '/img/futbolistas/isco.png', '1992-04-21', '2023-08-01', 'España', 22, 350000, 1, 'JUGADOR');
INSERT INTO futbolista (id, nombre, apellidos, img_futbolista, fecha_nacimiento, fecha_inicio_contrato, nacionalidad, num_camiseta, salario_mensual_base, equipo_id, tipo) VALUES (103, 'Ayoze', 'Pérez', '/img/futbolistas/ayoze_perez.jpg', '1993-07-29', '2023-07-01', 'España', 10, 220000, 1, 'JUGADOR');
INSERT INTO futbolista (id, nombre, apellidos, img_futbolista, fecha_nacimiento, fecha_inicio_contrato, nacionalidad, num_camiseta, salario_mensual_base, equipo_id, tipo) VALUES (104, 'Guido', 'Rodríguez', '/img/futbolistas/guido_rodriguez.jpg', '1994-04-12', '2019-01-01', 'Argentina', 5, 250000, 1, 'JUGADOR');
INSERT INTO futbolista (id, nombre, apellidos, img_futbolista, fecha_nacimiento, fecha_inicio_contrato, nacionalidad, num_camiseta, salario_mensual_base, equipo_id, tipo) VALUES (105, 'Abde', 'Ezzalzouli', '/img/futbolistas/abde.png', '2001-11-17', '2023-07-01', 'Marruecos', 10, 90000, 1, 'JUGADOR');
INSERT INTO futbolista (id, nombre, apellidos, img_futbolista, fecha_nacimiento, fecha_inicio_contrato, nacionalidad, num_camiseta, salario_mensual_base, equipo_id, tipo) VALUES (106, 'Chimy', 'Ávila', '/img/futbolistas/chimy_avila.png', '1994-10-04', '2023-07-01', 'Argentina', 9, 160000, 1, 'JUGADOR');
INSERT INTO futbolista (id, nombre, apellidos, img_futbolista, fecha_nacimiento, fecha_inicio_contrato, nacionalidad, num_camiseta, salario_mensual_base, equipo_id, tipo) VALUES (107, 'Cucho', 'Hernández', '/img/futbolistas/cucho.png', '1999-04-01', '2024-07-01', 'Colombia', 19, 120000, 1, 'JUGADOR');
INSERT INTO futbolista (id, nombre, apellidos, img_futbolista, fecha_nacimiento, fecha_inicio_contrato, nacionalidad, num_camiseta, salario_mensual_base, equipo_id, tipo) VALUES (108, 'Marc', 'Bartra', '/img/futbolistas/marc_bartra.png', '1991-01-07', '2023-08-01', 'España', 5, 140000, 1, 'JUGADOR');
INSERT INTO futbolista (id, nombre, apellidos, img_futbolista, fecha_nacimiento, fecha_inicio_contrato, nacionalidad, num_camiseta, salario_mensual_base, equipo_id, tipo) VALUES (109, 'Héctor', 'Bellerín', '/img/futbolistas/hector_bellerin.png', '1995-03-19', '2024-07-01', 'España', 2, 150000, 1, 'JUGADOR');
INSERT INTO futbolista (id, nombre, apellidos, img_futbolista, fecha_nacimiento, fecha_inicio_contrato, nacionalidad, num_camiseta, salario_mensual_base, equipo_id, tipo) VALUES (110, 'Marc', 'Roca', '/img/futbolistas/marc_roca.png', '1996-11-26', '2023-07-01', 'España', 21, 90000, 1, 'JUGADOR');
INSERT INTO futbolista (id, nombre, apellidos, img_futbolista, fecha_nacimiento, fecha_inicio_contrato, nacionalidad, num_camiseta, salario_mensual_base, equipo_id, tipo) VALUES (111, 'Pablo', 'Fornals', '/img/futbolistas/pablo_fornals.png', '1996-05-22', '2023-07-01', 'España', 18, 130000, 1, 'JUGADOR');
INSERT INTO futbolista (id, nombre, apellidos, img_futbolista, fecha_nacimiento, fecha_inicio_contrato, nacionalidad, num_camiseta, salario_mensual_base, equipo_id, tipo) VALUES (112, 'William', 'Carvalho', '/img/futbolistas/william_carvalho.png', '1992-04-07', '2023-07-01', 'Portugal', 14, 170000, 1, 'JUGADOR');
INSERT INTO futbolista (id, nombre, apellidos, img_futbolista, fecha_nacimiento, fecha_inicio_contrato, nacionalidad, num_camiseta, salario_mensual_base, equipo_id, tipo) VALUES (113, 'Giovani', 'Lo Celso', '/img/futbolistas/lo_celso.png', '1996-04-09', '2024-07-01', 'Argentina', 20, 160000, 1, 'JUGADOR');
INSERT INTO futbolista (id, nombre, apellidos, img_futbolista, fecha_nacimiento, fecha_inicio_contrato, nacionalidad, num_camiseta, salario_mensual_base, equipo_id, tipo) VALUES (114, 'Rui', 'Silva (suplente2)', '/img/futbolistas/rui_silva2.png', '1998-01-01', '2024-07-01', 'Portugal', 31, 60000, 1, 'PORTERO');
INSERT INTO futbolista (id, nombre, apellidos, img_futbolista, fecha_nacimiento, fecha_inicio_contrato, nacionalidad, num_camiseta, salario_mensual_base, equipo_id, tipo) VALUES (115, 'Assane', 'Diao', '/img/futbolistas/assane_diao.png', '2005-11-05', '2023-07-01', 'Senegal', 28, 50000, 1, 'JUGADOR');
INSERT INTO futbolista (id, nombre, apellidos, img_futbolista, fecha_nacimiento, fecha_inicio_contrato, nacionalidad, num_camiseta, salario_mensual_base, equipo_id, tipo) VALUES (116, 'Aitor', 'Ruibal', '/img/futbolistas/aitor_ruibal.png', '1996-02-02', '2023-07-01', 'España', 24, 70000, 1, 'JUGADOR');
INSERT INTO futbolista (id, nombre, apellidos, img_futbolista, fecha_nacimiento, fecha_inicio_contrato, nacionalidad, num_camiseta, salario_mensual_base, equipo_id, tipo) VALUES (117, 'Cédric', 'Bakambu', '/img/futbolistas/bakambu.png', '1987-11-11', '2024-07-01', 'RD Congo', 11, 200000, 1, 'JUGADOR');
INSERT INTO futbolista (id, nombre, apellidos, img_futbolista, fecha_nacimiento, fecha_inicio_contrato, nacionalidad, num_camiseta, salario_mensual_base, equipo_id, tipo) VALUES (118, 'Diego', 'Llorente', '/img/futbolistas/diego_llorente.png', '1993-08-16', '2022-07-01', 'España', 3, 120000, 1, 'JUGADOR');
INSERT INTO futbolista (id, nombre, apellidos, img_futbolista, fecha_nacimiento, fecha_inicio_contrato, nacionalidad, num_camiseta, salario_mensual_base, equipo_id, tipo) VALUES (119, 'Natan', 'Silva', '/img/futbolistas/natan.png', '2000-01-19', '2022-07-01', 'Brasil', 6, 110000, 1, 'JUGADOR');
INSERT INTO futbolista (id, nombre, apellidos, img_futbolista, fecha_nacimiento, fecha_inicio_contrato, nacionalidad, num_camiseta, salario_mensual_base, equipo_id, tipo) VALUES (120, 'Jesús', 'Cabrera', '/img/futbolistas/jesus_cabrera.png', '2002-05-10', '2024-07-01', 'España', 27, 45000, 1, 'JUGADOR');

-- Estadísticas (Real Betis primer equipo) (ids 2000-2029)
-- Note: where public reliable stats were missing, values were invented per your instruction; NULL left only when logically unknown.
INSERT INTO estadisticas (id, futbolista_id, min_jugados, tar_amarilla, tar_roja, calificacion, goles, asistencias, paradas, porteriasacero, dtype) VALUES (2000, 101, 2700, 3, 0, 7.2, NULL, NULL, 88, 10, 'EstadisticasPortero');
INSERT INTO estadisticas (id, futbolista_id, min_jugados, tar_amarilla, tar_roja, calificacion, goles, asistencias, paradas, porteriasacero, dtype) VALUES (2001, 102, 1850, 2, 0, 7.8, 4, 6, NULL, NULL, 'EstadisticasJugador');
INSERT INTO estadisticas (id, futbolista_id, min_jugados, tar_amarilla, tar_roja, calificacion, goles, asistencias, paradas, porteriasacero, dtype) VALUES (2002, 103, 2200, 4, 0, 7.6, 18, 5, NULL, NULL, 'EstadisticasJugador');
INSERT INTO estadisticas (id, futbolista_id, min_jugados, tar_amarilla, tar_roja, calificacion, goles, asistencias, paradas, porteriasacero, dtype) VALUES (2003, 104, 2400, 7, 1, 7.3, 0, 2, NULL, NULL, 'EstadisticasJugador');
INSERT INTO estadisticas (id, futbolista_id, min_jugados, tar_amarilla, tar_roja, calificacion, goles, asistencias, paradas, porteriasacero, dtype) VALUES (2004, 105, 1950, 3, 0, 7.1, 9, 4, NULL, NULL, 'EstadisticasJugador');
INSERT INTO estadisticas (id, futbolista_id, min_jugados, tar_amarilla, tar_roja, calificacion, goles, asistencias, paradas, porteriasacero, dtype) VALUES (2005, 106, 1500, 5, 0, 6.9, 6, 2, NULL, NULL, 'EstadisticasJugador');
INSERT INTO estadisticas (id, futbolista_id, min_jugados, tar_amarilla, tar_roja, calificacion, goles, asistencias, paradas, porteriasacero, dtype) VALUES (2006, 107, 800, 1, 0, 6.8, 3, 1, NULL, NULL, 'EstadisticasJugador');
INSERT INTO estadisticas (id, futbolista_id, min_jugados, tar_amarilla, tar_roja, calificacion, goles, asistencias, paradas, porteriasacero, dtype) VALUES (2007, 108, 2300, 6, 0, 7.4, 2, 1, NULL, NULL, 'EstadisticasJugador');
INSERT INTO estadisticas (id, futbolista_id, min_jugados, tar_amarilla, tar_roja, calificacion, goles, asistencias, paradas, porteriasacero, dtype) VALUES (2008, 109, 1200, 2, 0, 7.0, 1, 3, NULL, NULL, 'EstadisticasJugador');
INSERT INTO estadisticas (id, futbolista_id, min_jugados, tar_amarilla, tar_roja, calificacion, goles, asistencias, paradas, porteriasacero, dtype) VALUES (2009, 110, 1700, 4, 0, 7.0, 1, 2, NULL, NULL, 'EstadisticasJugador');
INSERT INTO estadisticas (id, futbolista_id, min_jugados, tar_amarilla, tar_roja, calificacion, goles, asistencias, paradas, porteriasacero, dtype) VALUES (2010, 111, 1600, 3, 0, 7.2, 5, 6, NULL, NULL, 'EstadisticasJugador');
INSERT INTO estadisticas (id, futbolista_id, min_jugados, tar_amarilla, tar_roja, calificacion, goles, asistencias, paradas, porteriasacero, dtype) VALUES (2011, 112, 2000, 5, 0, 7.1, 2, 3, NULL, NULL, 'EstadisticasJugador');
INSERT INTO estadisticas (id, futbolista_id, min_jugados, tar_amarilla, tar_roja, calificacion, goles, asistencias, paradas, porteriasacero, dtype) VALUES (2012, 113, 900, 2, 0, 6.9, 3, 1, NULL, NULL, 'EstadisticasJugador');
INSERT INTO estadisticas (id, futbolista_id, min_jugados, tar_amarilla, tar_roja, calificacion, goles, asistencias, paradas, porteriasacero, dtype) VALUES (2013, 114, 300, 0, 0, 6.5, NULL, NULL, 12, 0, 'EstadisticasPortero');
INSERT INTO estadisticas (id, futbolista_id, min_jugados, tar_amarilla, tar_roja, calificacion, goles, asistencias, paradas, porteriasacero, dtype) VALUES (2014, 115, 450, 1, 0, 6.7, 1, 0, NULL, NULL, 'EstadisticasJugador');
INSERT INTO estadisticas (id, futbolista_id, min_jugados, tar_amarilla, tar_roja, calificacion, goles, asistencias, paradas, porteriasacero, dtype) VALUES (2015, 116, 1200, 4, 0, 6.8, 2, 3, NULL, NULL, 'EstadisticasJugador');
INSERT INTO estadisticas (id, futbolista_id, min_jugados, tar_amarilla, tar_roja, calificacion, goles, asistencias, paradas, porteriasacero, dtype) VALUES (2016, 117, 600, 2, 0, 6.9, 5, 1, NULL, NULL, 'EstadisticasJugador');
INSERT INTO estadisticas (id, futbolista_id, min_jugados, tar_amarilla, tar_roja, calificacion, goles, asistencias, paradas, porteriasacero, dtype) VALUES (2017, 118, 1800, 3, 0, 7.1, 0, 1, NULL, NULL, 'EstadisticasJugador');
INSERT INTO estadisticas (id, futbolista_id, min_jugados, tar_amarilla, tar_roja, calificacion, goles, asistencias, paradas, porteriasacero, dtype) VALUES (2018, 119, 1400, 5, 0, 6.9, 1, 0, NULL, NULL, 'EstadisticasJugador');
INSERT INTO estadisticas (id, futbolista_id, min_jugados, tar_amarilla, tar_roja, calificacion, goles, asistencias, paradas, porteriasacero, dtype) VALUES (2019, 120, 400, 1, 0, 6.6, 0, 0, NULL, NULL, 'EstadisticasJugador');

-- Betis Deportivo (Real Betis B) players (IDs 201-235)
INSERT INTO futbolista (id, nombre, apellidos, img_futbolista, fecha_nacimiento, fecha_inicio_contrato, nacionalidad, num_camiseta, salario_mensual_base, equipo_id, tipo) VALUES (201, 'Sergio', 'Soler', '/img/futbolistas/sergio_soler.png', '2001-03-12', '2023-07-01', 'España', 1, 2500, 2, 'PORTERO');
INSERT INTO futbolista (id, nombre, apellidos, img_futbolista, fecha_nacimiento, fecha_inicio_contrato, nacionalidad, num_camiseta, salario_mensual_base, equipo_id, tipo) VALUES (202, 'Pablo', 'García', '/img/futbolistas/pablo_garcia_bd.png', '2002-04-05', '2022-07-01', 'España', 2, 3500, 2, 'JUGADOR');
INSERT INTO futbolista (id, nombre, apellidos, img_futbolista, fecha_nacimiento, fecha_inicio_contrato, nacionalidad, num_camiseta, salario_mensual_base, equipo_id, tipo) VALUES (203, 'Óscar', 'Martínez', '/img/futbolistas/oscar_martinez.png', '2000-02-20', '2021-07-01', 'España', 3, 3000, 2, 'JUGADOR');
INSERT INTO futbolista (id, nombre, apellidos, img_futbolista, fecha_nacimiento, fecha_inicio_contrato, nacionalidad, num_camiseta, salario_mensual_base, equipo_id, tipo) VALUES (204, 'Iván', 'López', '/img/futbolistas/ivan_lopez.png', '2003-08-11', '2023-07-01', 'España', 4, 2800, 2, 'JUGADOR');
INSERT INTO futbolista (id, nombre, apellidos, img_futbolista, fecha_nacimiento, fecha_inicio_contrato, nacionalidad, num_camiseta, salario_mensual_base, equipo_id, tipo) VALUES (205, 'Diego', 'Morales', '/img/futbolistas/diego_morales.png', '2001-09-07', '2022-07-01', 'España', 5, 3200, 2, 'JUGADOR');
INSERT INTO futbolista (id, nombre, apellidos, img_futbolista, fecha_nacimiento, fecha_inicio_contrato, nacionalidad, num_camiseta, salario_mensual_base, equipo_id, tipo) VALUES (206, 'Carlos', 'Suárez', '/img/futbolistas/carlos_suarez.png', '2002-11-16', '2023-07-01', 'España', 6, 3000, 2, 'JUGADOR');
INSERT INTO futbolista (id, nombre, apellidos, img_futbolista, fecha_nacimiento, fecha_inicio_contrato, nacionalidad, num_camiseta, salario_mensual_base, equipo_id, tipo) VALUES (207, 'Ángel', 'Rivera', '/img/futbolistas/angel_rivera.png', '2004-01-03', '2024-01-01', 'España', 7, 2200, 2, 'JUGADOR');
INSERT INTO futbolista (id, nombre, apellidos, img_futbolista, fecha_nacimiento, fecha_inicio_contrato, nacionalidad, num_camiseta, salario_mensual_base, equipo_id, tipo) VALUES (208, 'Lucas', 'Gómez', '/img/futbolistas/lucas_gomez.png', '2000-06-22', '2024-07-01', 'España', 8, 3300, 2, 'JUGADOR');
INSERT INTO futbolista (id, nombre, apellidos, img_futbolista, fecha_nacimiento, fecha_inicio_contrato, nacionalidad, num_camiseta, salario_mensual_base, equipo_id, tipo) VALUES (209, 'Diego', 'Sánchez', '/img/futbolistas/diego_sanchez.png', '2003-12-01', '2023-07-01', 'España', 9, 2600, 2, 'JUGADOR');
INSERT INTO futbolista (id, nombre, apellidos, img_futbolista, fecha_nacimiento, fecha_inicio_contrato, nacionalidad, num_camiseta, salario_mensual_base, equipo_id, tipo) VALUES (210, 'Óliver', 'Fernández', '/img/futbolistas/oliver_fernandez.png', '2002-05-30', '2022-07-01', 'España', 10, 2900, 2, 'JUGADOR');
INSERT INTO futbolista (id, nombre, apellidos, img_futbolista, fecha_nacimiento, fecha_inicio_contrato, nacionalidad, num_camiseta, salario_mensual_base, equipo_id, tipo) VALUES (211, 'Samuel', 'Díaz', '/img/futbolistas/samuel_diaz.png', '2001-07-15', '2023-07-01', 'España', 11, 2800, 2, 'JUGADOR');
INSERT INTO futbolista (id, nombre, apellidos, img_futbolista, fecha_nacimiento, fecha_inicio_contrato, nacionalidad, num_camiseta, salario_mensual_base, equipo_id, tipo) VALUES (212, 'Miguel', 'Pérez', '/img/futbolistas/miguel_perez.png', '2004-10-10', '2024-07-01', 'España', 12, 2000, 2, 'JUGADOR');
INSERT INTO futbolista (id, nombre, apellidos, img_futbolista, fecha_nacimiento, fecha_inicio_contrato, nacionalidad, num_camiseta, salario_mensual_base, equipo_id, tipo) VALUES (213, 'Iker', 'Martín', '/img/futbolistas/iker_martin.png', '2001-02-28', '2023-07-01', 'España', 13, 2600, 2, 'JUGADOR');
INSERT INTO futbolista (id, nombre, apellidos, img_futbolista, fecha_nacimiento, fecha_inicio_contrato, nacionalidad, num_camiseta, salario_mensual_base, equipo_id, tipo) VALUES (214, 'Adrián', 'González', '/img/futbolistas/adrian_gonzalez.png', '2000-08-08', '2022-07-01', 'España', 14, 3000, 2, 'JUGADOR');
INSERT INTO futbolista (id, nombre, apellidos, img_futbolista, fecha_nacimiento, fecha_inicio_contrato, nacionalidad, num_camiseta, salario_mensual_base, equipo_id, tipo) VALUES (215, 'Raúl', 'Hernández', '/img/futbolistas/raul_hernandez.png', '2002-03-02', '2023-07-01', 'España', 15, 2700, 2, 'JUGADOR');
INSERT INTO futbolista (id, nombre, apellidos, img_futbolista, fecha_nacimiento, fecha_inicio_contrato, nacionalidad, num_camiseta, salario_mensual_base, equipo_id, tipo) VALUES (216, 'Sergio', 'Jiménez', '/img/futbolistas/sergio_jimenez.png', '2003-11-11', '2024-07-01', 'España', 16, 2200, 2, 'JUGADOR');
INSERT INTO futbolista (id, nombre, apellidos, img_futbolista, fecha_nacimiento, fecha_inicio_contrato, nacionalidad, num_camiseta, salario_mensual_base, equipo_id, tipo) VALUES (217, 'Rubén', 'Alonso', '/img/futbolistas/ruben_alonso.png', '2001-05-04', '2022-07-01', 'España', 17, 3100, 2, 'JUGADOR');
INSERT INTO futbolista (id, nombre, apellidos, img_futbolista, fecha_nacimiento, fecha_inicio_contrato, nacionalidad, num_camiseta, salario_mensual_base, equipo_id, tipo) VALUES (218, 'Óscar', 'Gil', '/img/futbolistas/oscar_gil.png', '2004-04-21', '2024-07-01', 'España', 18, 2000, 2, 'JUGADOR');
INSERT INTO futbolista (id, nombre, apellidos, img_futbolista, fecha_nacimiento, fecha_inicio_contrato, nacionalidad, num_camiseta, salario_mensual_base, equipo_id, tipo) VALUES (219, 'Mario', 'Vega', '/img/futbolistas/mario_vega.png', '2002-09-18', '2023-07-01', 'España', 19, 2500, 2, 'JUGADOR');
INSERT INTO futbolista (id, nombre, apellidos, img_futbolista, fecha_nacimiento, fecha_inicio_contrato, nacionalidad, num_camiseta, salario_mensual_base, equipo_id, tipo) VALUES (220, 'Antonio', 'Lopez', '/img/futbolistas/antonio_lopez.png', '2000-12-12', '2022-07-01', 'España', 20, 2800, 2, 'JUGADOR');
INSERT INTO futbolista (id, nombre, apellidos, img_futbolista, fecha_nacimiento, fecha_inicio_contrato, nacionalidad, num_camiseta, salario_mensual_base, equipo_id, tipo) VALUES (221, 'Jorge', 'Navarro', '/img/futbolistas/jorge_navarro.png', '2001-06-06', '2023-07-01', 'España', 21, 2600, 2, 'JUGADOR');
INSERT INTO futbolista (id, nombre, apellidos, img_futbolista, fecha_nacimiento, fecha_inicio_contrato, nacionalidad, num_camiseta, salario_mensual_base, equipo_id, tipo) VALUES (222, 'Iván', 'Herrera', '/img/futbolistas/ivan_herrera.png', '2003-09-09', '2024-07-01', 'España', 22, 2100, 2, 'JUGADOR');
INSERT INTO futbolista (id, nombre, apellidos, img_futbolista, fecha_nacimiento, fecha_inicio_contrato, nacionalidad, num_camiseta, salario_mensual_base, equipo_id, tipo) VALUES (223, 'Kike', 'Moreno', '/img/futbolistas/kike_moreno.png', '2002-02-02', '2023-07-01', 'España', 23, 2400, 2, 'JUGADOR');
INSERT INTO futbolista (id, nombre, apellidos, img_futbolista, fecha_nacimiento, fecha_inicio_contrato, nacionalidad, num_camiseta, salario_mensual_base, equipo_id, tipo) VALUES (224, 'Rubén', 'Prieto', '/img/futbolistas/ruben_prieto.png', '2001-07-07', '2023-07-01', 'España', 24, 2600, 2, 'JUGADOR');
INSERT INTO futbolista (id, nombre, apellidos, img_futbolista, fecha_nacimiento, fecha_inicio_contrato, nacionalidad, num_camiseta, salario_mensual_base, equipo_id, tipo) VALUES (225, 'Adrián', 'Ruiz', '/img/futbolistas/adrian_ruiz.png', '2004-11-11', '2024-07-01', 'España', 25, 1800, 2, 'JUGADOR');

-- Estadísticas (Betis Deportivo) (ids 3000-3024) -- many lower-division stats invented when not found
INSERT INTO estadisticas (id, futbolista_id, min_jugados, tar_amarilla, tar_roja, calificacion, goles, asistencias, paradas, porteriasacero, dtype) VALUES (3000, 201, 2700, 4, 0, 7.0, NULL, NULL, 90, 12, 'EstadisticasPortero');
INSERT INTO estadisticas (id, futbolista_id, min_jugados, tar_amarilla, tar_roja, calificacion, goles, asistencias, paradas, porteriasacero, dtype) VALUES (3001, 202, 2100, 6, 0, 7.1, 6, 4, NULL, NULL, 'EstadisticasJugador');
INSERT INTO estadisticas (id, futbolista_id, min_jugados, tar_amarilla, tar_roja, calificacion, goles, asistencias, paradas, porteriasacero, dtype) VALUES (3002, 203, 1800, 3, 0, 6.8, 4, 2, NULL, NULL, 'EstadisticasJugador');
INSERT INTO estadisticas (id, futbolista_id, min_jugados, tar_amarilla, tar_roja, calificacion, goles, asistencias, paradas, porteriasacero, dtype) VALUES (3003, 204, 1600, 2, 0, 6.7, 2, 3, NULL, NULL, 'EstadisticasJugador');
INSERT INTO estadisticas (id, futbolista_id, min_jugados, tar_amarilla, tar_roja, calificacion, goles, asistencias, paradas, porteriasacero, dtype) VALUES (3004, 205, 2000, 5, 0, 7.0, 8, 6, NULL, NULL, 'EstadisticasJugador');
INSERT INTO estadisticas (id, futbolista_id, min_jugados, tar_amarilla, tar_roja, calificacion, goles, asistencias, paradas, porteriasacero, dtype) VALUES (3005, 206, 1500, 4, 0, 6.9, 3, 1, NULL, NULL, 'EstadisticasJugador');
INSERT INTO estadisticas (id, futbolista_id, min_jugados, tar_amarilla, tar_roja, calificacion, goles, asistencias, paradas, porteriasacero, dtype) VALUES (3006, 207, 900, 1, 0, 6.5, 1, 0, NULL, NULL, 'EstadisticasJugador');
INSERT INTO estadisticas (id, futbolista_id, min_jugados, tar_amarilla, tar_roja, calificacion, goles, asistencias, paradas, porteriasacero, dtype) VALUES (3007, 208, 1750, 3, 0, 6.9, 5, 2, NULL, NULL, 'EstadisticasJugador');
INSERT INTO estadisticas (id, futbolista_id, min_jugados, tar_amarilla, tar_roja, calificacion, goles, asistencias, paradas, porteriasacero, dtype) VALUES (3008, 209, 1200, 2, 0, 6.6, 2, 1, NULL, NULL, 'EstadisticasJugador');
INSERT INTO estadisticas (id, futbolista_id, min_jugados, tar_amarilla, tar_roja, calificacion, goles, asistencias, paradas, porteriasacero, dtype) VALUES (3009, 210, 1400, 3, 0, 6.8, 4, 3, NULL, NULL, 'EstadisticasJugador');
INSERT INTO estadisticas (id, futbolista_id, min_jugados, tar_amarilla, tar_roja, calificacion, goles, asistencias, paradas, porteriasacero, dtype) VALUES (3010, 211, 1300, 4, 0, 6.9, 3, 2, NULL, NULL, 'EstadisticasJugador');
INSERT INTO estadisticas (id, futbolista_id, min_jugados, tar_amarilla, tar_roja, calificacion, goles, asistencias, paradas, porteriasacero, dtype) VALUES (3011, 212, 400, 1, 0, 6.4, 0, 0, NULL, NULL, 'EstadisticasJugador');
INSERT INTO estadisticas (id, futbolista_id, min_jugados, tar_amarilla, tar_roja, calificacion, goles, asistencias, paradas, porteriasacero, dtype) VALUES (3012, 213, 1600, 3, 0, 6.8, 6, 4, NULL, NULL, 'EstadisticasJugador');
INSERT INTO estadisticas (id, futbolista_id, min_jugados, tar_amarilla, tar_roja, calificacion, goles, asistencias, paradas, porteriasacero, dtype) VALUES (3013, 214, 1500, 5, 0, 6.7, 4, 2, NULL, NULL, 'EstadisticasJugador');
INSERT INTO estadisticas (id, futbolista_id, min_jugados, tar_amarilla, tar_roja, calificacion, goles, asistencias, paradas, porteriasacero, dtype) VALUES (3014, 215, 1700, 2, 0, 7.0, 7, 3, NULL, NULL, 'EstadisticasJugador');
INSERT INTO estadisticas (id, futbolista_id, min_jugados, tar_amarilla, tar_roja, calificacion, goles, asistencias, paradas, porteriasacero, dtype) VALUES (3015, 216, 800, 1, 0, 6.5, 1, 0, NULL, NULL, 'EstadisticasJugador');
INSERT INTO estadisticas (id, futbolista_id, min_jugados, tar_amarilla, tar_roja, calificacion, goles, asistencias, paradas, porteriasacero, dtype) VALUES (3016, 217, 1100, 3, 0, 6.7, 2, 1, NULL, NULL, 'EstadisticasJugador');
INSERT INTO estadisticas (id, futbolista_id, min_jugados, tar_amarilla, tar_roja, calificacion, goles, asistencias, paradas, porteriasacero, dtype) VALUES (3017, 218, 600, 2, 0, 6.4, 0, 0, NULL, NULL, 'EstadisticasJugador');
INSERT INTO estadisticas (id, futbolista_id, min_jugados, tar_amarilla, tar_roja, calificacion, goles, asistencias, paradas, porteriasacero, dtype) VALUES (3018, 219, 900, 1, 0, 6.6, 2, 1, NULL, NULL, 'EstadisticasJugador');
INSERT INTO estadisticas (id, futbolista_id, min_jugados, tar_amarilla, tar_roja, calificacion, goles, asistencias, paradas, porteriasacero, dtype) VALUES (3019, 220, 1400, 4, 0, 6.9, 5, 4, NULL, NULL, 'EstadisticasJugador');
INSERT INTO estadisticas (id, futbolista_id, min_jugados, tar_amarilla, tar_roja, calificacion, goles, asistencias, paradas, porteriasacero, dtype) VALUES (3020, 221, 1300, 3, 0, 6.8, 4, 2, NULL, NULL, 'EstadisticasJugador');
INSERT INTO estadisticas (id, futbolista_id, min_jugados, tar_amarilla, tar_roja, calificacion, goles, asistencias, paradas, porteriasacero, dtype) VALUES (3021, 222, 500, 1, 0, 6.3, 0, 1, NULL, NULL, 'EstadisticasJugador');
INSERT INTO estadisticas (id, futbolista_id, min_jugados, tar_amarilla, tar_roja, calificacion, goles, asistencias, paradas, porteriasacero, dtype) VALUES (3022, 223, 1000, 2, 0, 6.7, 3, 1, NULL, NULL, 'EstadisticasJugador');
INSERT INTO estadisticas (id, futbolista_id, min_jugados, tar_amarilla, tar_roja, calificacion, goles, asistencias, paradas, porteriasacero, dtype) VALUES (3023, 224, 700, 2, 0, 6.5, 1, 0, NULL, NULL, 'EstadisticasJugador');
INSERT INTO estadisticas (id, futbolista_id, min_jugados, tar_amarilla, tar_roja, calificacion, goles, asistencias, paradas, porteriasacero, dtype) VALUES (3024, 225, 200, 0, 0, 6.0, 0, 0, NULL, NULL, 'EstadisticasJugador');

-- Real Betis Féminas players (IDs 301-335)
INSERT INTO futbolista (id, nombre, apellidos, img_futbolista, fecha_nacimiento, fecha_inicio_contrato, nacionalidad, num_camiseta, salario_mensual_base, equipo_id, tipo) VALUES (301, 'Catalina', 'Usme', '/img/futbolistas/catalina_usme.png', '1989-12-21', '2024-08-01', 'Colombia', 9, 8000, 3, 'JUGADOR');
INSERT INTO futbolista (id, nombre, apellidos, img_futbolista, fecha_nacimiento, fecha_inicio_contrato, nacionalidad, num_camiseta, salario_mensual_base, equipo_id, tipo) VALUES (302, 'Laia', 'Codina', '/img/futbolistas/laia_codina.png', '1999-07-27', '2023-07-01', 'España', 2, 7000, 3, 'JUGADOR');
INSERT INTO futbolista (id, nombre, apellidos, img_futbolista, fecha_nacimiento, fecha_inicio_contrato, nacionalidad, num_camiseta, salario_mensual_base, equipo_id, tipo) VALUES (303, 'Analu', 'Pachón', '/img/futbolistas/analu_pachon.png', '1998-05-09', '2022-07-01', 'España', 6, 6000, 3, 'JUGADOR');
INSERT INTO futbolista (id, nombre, apellidos, img_futbolista, fecha_nacimiento, fecha_inicio_contrato, nacionalidad, num_camiseta, salario_mensual_base, equipo_id, tipo) VALUES (304, 'Salma', 'Paralluelo', '/img/futbolistas/salma_paralluelo.png', '2003-08-13', '2024-07-01', 'España', 11, 9000, 3, 'JUGADOR');
INSERT INTO futbolista (id, nombre, apellidos, img_futbolista, fecha_nacimiento, fecha_inicio_contrato, nacionalidad, num_camiseta, salario_mensual_base, equipo_id, tipo) VALUES (305, 'Vanesa', 'González', '/img/futbolistas/vanesa_gonzalez.png', '1996-02-17', '2021-07-01', 'España', 8, 5500, 3, 'JUGADOR');
INSERT INTO futbolista (id, nombre, apellidos, img_futbolista, fecha_nacimiento, fecha_inicio_contrato, nacionalidad, num_camiseta, salario_mensual_base, equipo_id, tipo) VALUES (306, 'Ainhoa', 'Morales', '/img/futbolistas/ainhoa_morales.png', '1997-03-05', '2023-07-01', 'España', 5, 6000, 3, 'JUGADOR');
INSERT INTO futbolista (id, nombre, apellidos, img_futbolista, fecha_nacimiento, fecha_inicio_contrato, nacionalidad, num_camiseta, salario_mensual_base, equipo_id, tipo) VALUES (307, 'Marta', 'Herrera', '/img/futbolistas/marta_herrera.png', '1995-10-10', '2022-07-01', 'España', 4, 5000, 3, 'JUGADOR');
INSERT INTO futbolista (id, nombre, apellidos, img_futbolista, fecha_nacimiento, fecha_inicio_contrato, nacionalidad, num_camiseta, salario_mensual_base, equipo_id, tipo) VALUES (308, 'Irene', 'García', '/img/futbolistas/irene_garcia.png', '2001-09-09', '2024-07-01', 'España', 3, 4800, 3, 'JUGADOR');
INSERT INTO futbolista (id, nombre, apellidos, img_futbolista, fecha_nacimiento, fecha_inicio_contrato, nacionalidad, num_camiseta, salario_mensual_base, equipo_id, tipo) VALUES (309, 'Laura', 'Ramos', '/img/futbolistas/laura_ramos.png', '1999-04-04', '2023-07-01', 'España', 7, 5200, 3, 'JUGADOR');
INSERT INTO futbolista (id, nombre, apellidos, img_futbolista, fecha_nacimiento, fecha_inicio_contrato, nacionalidad, num_camiseta, salario_mensual_base, equipo_id, tipo) VALUES (310, 'Noelia', 'Martín', '/img/futbolistas/noelia_martin.png', '1998-11-11', '2022-07-01', 'España', 1, 7500, 3, 'PORTERO');
INSERT INTO futbolista (id, nombre, apellidos, img_futbolista, fecha_nacimiento, fecha_inicio_contrato, nacionalidad, num_camiseta, salario_mensual_base, equipo_id, tipo) VALUES (311, 'Miriam', 'Pérez', '/img/futbolistas/miriam_perez.png', '2000-06-06', '2023-07-01', 'España', 12, 4500, 3, 'JUGADOR');
INSERT INTO futbolista (id, nombre, apellidos, img_futbolista, fecha_nacimiento, fecha_inicio_contrato, nacionalidad, num_camiseta, salario_mensual_base, equipo_id, tipo) VALUES (312, 'Patricia', 'Lopez', '/img/futbolistas/patricia_lopez.png', '1997-02-02', '2021-07-01', 'España', 13, 5200, 3, 'JUGADOR');
INSERT INTO futbolista (id, nombre, apellidos, img_futbolista, fecha_nacimiento, fecha_inicio_contrato, nacionalidad, num_camiseta, salario_mensual_base, equipo_id, tipo) VALUES (313, 'Elena', 'Sánchez', '/img/futbolistas/elena_sanchez.png', '1996-12-12', '2022-07-01', 'España', 14, 5300, 3, 'JUGADOR');
INSERT INTO futbolista (id, nombre, apellidos, img_futbolista, fecha_nacimiento, fecha_inicio_contrato, nacionalidad, num_camiseta, salario_mensual_base, equipo_id, tipo) VALUES (314, 'Andrea', 'Cano', '/img/futbolistas/andrea_cano.png', '2003-03-03', '2024-07-01', 'España', 15, 4000, 3, 'JUGADOR');
INSERT INTO futbolista (id, nombre, apellidos, img_futbolista, fecha_nacimiento, fecha_inicio_contrato, nacionalidad, num_camiseta, salario_mensual_base, equipo_id, tipo) VALUES (315, 'Nerea', 'Gil', '/img/futbolistas/nerea_gil.png', '2002-05-05', '2023-07-01', 'España', 16, 4200, 3, 'JUGADOR');
INSERT INTO futbolista (id, nombre, apellidos, img_futbolista, fecha_nacimiento, fecha_inicio_contrato, nacionalidad, num_camiseta, salario_mensual_base, equipo_id, tipo) VALUES (316, 'Carla', 'Domínguez', '/img/futbolistas/carla_dominguez.png', '2001-01-01', '2022-07-01', 'España', 17, 4500, 3, 'JUGADOR');
INSERT INTO futbolista (id, nombre, apellidos, img_futbolista, fecha_nacimiento, fecha_inicio_contrato, nacionalidad, num_camiseta, salario_mensual_base, equipo_id, tipo) VALUES (317, 'Raquel', 'Moreno', '/img/futbolistas/raquel_moreno.png', '1995-05-05', '2021-07-01', 'España', 18, 6000, 3, 'JUGADOR');
INSERT INTO futbolista (id, nombre, apellidos, img_futbolista, fecha_nacimiento, fecha_inicio_contrato, nacionalidad, num_camiseta, salario_mensual_base, equipo_id, tipo) VALUES (318, 'Silvia', 'Navarro', '/img/futbolistas/silvia_navarro.png', '1994-09-09', '2023-07-01', 'España', 19, 5800, 3, 'JUGADOR');
INSERT INTO futbolista (id, nombre, apellidos, img_futbolista, fecha_nacimiento, fecha_inicio_contrato, nacionalidad, num_camiseta, salario_mensual_base, equipo_id, tipo) VALUES (319, 'Marta', 'Lopez', '/img/futbolistas/marta_lopez.png', '1999-07-07', '2024-07-01', 'España', 20, 4700, 3, 'JUGADOR');
INSERT INTO futbolista (id, nombre, apellidos, img_futbolista, fecha_nacimiento, fecha_inicio_contrato, nacionalidad, num_camiseta, salario_mensual_base, equipo_id, tipo) VALUES (320, 'Ariadna', 'Vila', '/img/futbolistas/ariadna_vila.png', '2000-02-02', '2023-07-01', 'España', 21, 4400, 3, 'JUGADOR');
INSERT INTO futbolista (id, nombre, apellidos, img_futbolista, fecha_nacimiento, fecha_inicio_contrato, nacionalidad, num_camiseta, salario_mensual_base, equipo_id, tipo) VALUES (321, 'Celia', 'Pérez', '/img/futbolistas/celia_perez.png', '2002-08-08', '2023-07-01', 'España', 22, 4300, 3, 'JUGADOR');
INSERT INTO futbolista (id, nombre, apellidos, img_futbolista, fecha_nacimiento, fecha_inicio_contrato, nacionalidad, num_camiseta, salario_mensual_base, equipo_id, tipo) VALUES (322, 'Lourdes', 'Martín', '/img/futbolistas/lourdes_martin.png', '2001-10-10', '2024-07-01', 'España', 23, 4100, 3, 'JUGADOR');
INSERT INTO futbolista (id, nombre, apellidos, img_futbolista, fecha_nacimiento, fecha_inicio_contrato, nacionalidad, num_camiseta, salario_mensual_base, equipo_id, tipo) VALUES (323, 'Belén', 'Rey', '/img/futbolistas/belen_rey.png', '1998-06-06', '2022-07-01', 'España', 24, 4800, 3, 'JUGADOR');
INSERT INTO futbolista (id, nombre, apellidos, img_futbolista, fecha_nacimiento, fecha_inicio_contrato, nacionalidad, num_camiseta, salario_mensual_base, equipo_id, tipo) VALUES (324, 'María', 'Hernández', '/img/futbolistas/maria_hernandez.png', '1997-03-03', '2021-07-01', 'España', 25, 5000, 3, 'JUGADOR');
INSERT INTO futbolista (id, nombre, apellidos, img_futbolista, fecha_nacimiento, fecha_inicio_contrato, nacionalidad, num_camiseta, salario_mensual_base, equipo_id, tipo) VALUES (325, 'Iris', 'Castro', '/img/futbolistas/iris_castro.png', '2003-11-11', '2024-07-01', 'España', 26, 3700, 3, 'JUGADOR');
INSERT INTO futbolista (id, nombre, apellidos, img_futbolista, fecha_nacimiento, fecha_inicio_contrato, nacionalidad, num_camiseta, salario_mensual_base, equipo_id, tipo) VALUES (326, 'Noa', 'Santos', '/img/futbolistas/noa_santos.png', '2004-12-12', '2024-07-01', 'España', 27, 3500, 3, 'JUGADOR');
INSERT INTO futbolista (id, nombre, apellidos, img_futbolista, fecha_nacimiento, fecha_inicio_contrato, nacionalidad, num_camiseta, salario_mensual_base, equipo_id, tipo) VALUES (327, 'Pat', 'Gómez', '/img/futbolistas/pat_gomez.png', '2002-01-01', '2023-07-01', 'España', 28, 3800, 3, 'JUGADOR');
INSERT INTO futbolista (id, nombre, apellidos, img_futbolista, fecha_nacimiento, fecha_inicio_contrato, nacionalidad, num_camiseta, salario_mensual_base, equipo_id, tipo) VALUES (328, 'Icíar', 'Molina', '/img/futbolistas/iciar_molina.png', '1996-08-08', '2021-07-01', 'España', 29, 5400, 3, 'JUGADOR');
INSERT INTO futbolista (id, nombre, apellidos, img_futbolista, fecha_nacimiento, fecha_inicio_contrato, nacionalidad, num_camiseta, salario_mensual_base, equipo_id, tipo) VALUES (329, 'Aroa', 'Gómez', '/img/futbolistas/aróa_gomez.png', '2000-09-09', '2023-07-01', 'España', 30, 4600, 3, 'JUGADOR');
INSERT INTO futbolista (id, nombre, apellidos, img_futbolista, fecha_nacimiento, fecha_inicio_contrato, nacionalidad, num_camiseta, salario_mensual_base, equipo_id, tipo) VALUES (330, 'Rocío', 'López', '/img/futbolistas/rocio_lopez.png', '1999-02-02', '2021-07-01', 'España', 31, 4800, 3, 'JUGADOR');
INSERT INTO futbolista (id, nombre, apellidos, img_futbolista, fecha_nacimiento, fecha_inicio_contrato, nacionalidad, num_camiseta, salario_mensual_base, equipo_id, tipo) VALUES (331, 'Sara', 'Vega', '/img/futbolistas/sara_vega.png', '1998-05-05', '2022-07-01', 'España', 32, 4700, 3, 'JUGADOR');
INSERT INTO futbolista (id, nombre, apellidos, img_futbolista, fecha_nacimiento, fecha_inicio_contrato, nacionalidad, num_camiseta, salario_mensual_base, equipo_id, tipo) VALUES (332, 'Noemí', 'Ramos', '/img/futbolistas/noemi_ramos.png', '2001-06-06', '2023-07-01', 'España', 33, 3600, 3, 'JUGADOR');
INSERT INTO futbolista (id, nombre, apellidos, img_futbolista, fecha_nacimiento, fecha_inicio_contrato, nacionalidad, num_camiseta, salario_mensual_base, equipo_id, tipo) VALUES (333, 'Lorena', 'Suárez', '/img/futbolistas/lorena_suarez.png', '1995-01-01', '2021-07-01', 'España', 34, 5200, 3, 'JUGADOR');
INSERT INTO futbolista (id, nombre, apellidos, img_futbolista, fecha_nacimiento, fecha_inicio_contrato, nacionalidad, num_camiseta, salario_mensual_base, equipo_id, tipo) VALUES (334, 'Olga', 'Vargas', '/img/futbolistas/olga_vargas.png', '1997-07-07', '2022-07-01', 'España', 35, 5100, 3, 'JUGADOR');
INSERT INTO futbolista (id, nombre, apellidos, img_futbolista, fecha_nacimiento, fecha_inicio_contrato, nacionalidad, num_camiseta, salario_mensual_base, equipo_id, tipo) VALUES (335, 'Mireia', 'Ortega', '/img/futbolistas/mireia_ortega.png', '2000-10-10', '2024-07-01', 'España', 36, 3900, 3, 'JUGADOR');

-- Estadísticas (Real Betis Féminas) (ids 4000-4034)
-- Mix of real-known and invented-statistics where not publicly available.
INSERT INTO estadisticas (id, futbolista_id, min_jugados, tar_amarilla, tar_roja, calificacion, goles, asistencias, paradas, porteriasacero, dtype) VALUES (4000, 301, 2100, 4, 0, 7.2, 12, 5, NULL, NULL, 'EstadisticasJugador');
INSERT INTO estadisticas (id, futbolista_id, min_jugados, tar_amarilla, tar_roja, calificacion, goles, asistencias, paradas, porteriasacero, dtype) VALUES (4001, 302, 2400, 3, 0, 7.4, 1, 3, NULL, NULL, 'EstadisticasJugador');
INSERT INTO estadisticas (id, futbolista_id, min_jugados, tar_amarilla, tar_roja, calificacion, goles, asistencias, paradas, porteriasacero, dtype) VALUES (4002, 303, 1800, 2, 0, 7.0, 0, 2, NULL, NULL, 'EstadisticasJugador');
INSERT INTO estadisticas (id, futbolista_id, min_jugados, tar_amarilla, tar_roja, calificacion, goles, asistencias, paradas, porteriasacero, dtype) VALUES (4003, 304, 1200, 1, 0, 6.9, 6, 2, NULL, NULL, 'EstadisticasJugador');
INSERT INTO estadisticas (id, futbolista_id, min_jugados, tar_amarilla, tar_roja, calificacion, goles, asistencias, paradas, porteriasacero, dtype) VALUES (4004, 305, 2000, 5, 0, 7.1, 4, 7, NULL, NULL, 'EstadisticasJugador');
INSERT INTO estadisticas (id, futbolista_id, min_jugados, tar_amarilla, tar_roja, calificacion, goles, asistencias, paradas, porteriasacero, dtype) VALUES (4005, 306, 1600, 3, 0, 6.8, 2, 3, NULL, NULL, 'EstadisticasJugador');
INSERT INTO estadisticas (id, futbolista_id, min_jugados, tar_amarilla, tar_roja, calificacion, goles, asistencias, paradas, porteriasacero, dtype) VALUES (4006, 307, 2000, 4, 0, 7.0, 1, 4, NULL, NULL, 'EstadisticasJugador');
INSERT INTO estadisticas (id, futbolista_id, min_jugados, tar_amarilla, tar_roja, calificacion, goles, asistencias, paradas, porteriasacero, dtype) VALUES (4007, 308, 1400, 2, 0, 6.7, 0, 1, NULL, NULL, 'EstadisticasJugador');
INSERT INTO estadisticas (id, futbolista_id, min_jugados, tar_amarilla, tar_roja, calificacion, goles, asistencias, paradas, porteriasacero, dtype) VALUES (4008, 309, 1500, 3, 0, 6.9, 3, 2, NULL, NULL, 'EstadisticasJugador');
INSERT INTO estadisticas (id, futbolista_id, min_jugados, tar_amarilla, tar_roja, calificacion, goles, asistencias, paradas, porteriasacero, dtype) VALUES (4009, 310, 2500, 1, 0, 7.3, NULL, NULL, 95, 14, 'EstadisticasPortero');
INSERT INTO estadisticas (id, futbolista_id, min_jugados, tar_amarilla, tar_roja, calificacion, goles, asistencias, paradas, porteriasacero, dtype) VALUES (4010, 311, 900, 1, 0, 6.5, 0, 0, NULL, NULL, 'EstadisticasJugador');
INSERT INTO estadisticas (id, futbolista_id, min_jugados, tar_amarilla, tar_roja, calificacion, goles, asistencias, paradas, porteriasacero, dtype) VALUES (4011, 312, 1700, 4, 0, 6.9, 2, 3, NULL, NULL, 'EstadisticasJugador');
INSERT INTO estadisticas (id, futbolista_id, min_jugados, tar_amarilla, tar_roja, calificacion, goles, asistencias, paradas, porteriasacero, dtype) VALUES (4012, 313, 1600, 3, 0, 7.0, 3, 2, NULL, NULL, 'EstadisticasJugador');
INSERT INTO estadisticas (id, futbolista_id, min_jugados, tar_amarilla, tar_roja, calificacion, goles, asistencias, paradas, porteriasacero, dtype) VALUES (4013, 314, 400, 0, 0, 6.2, 0, 0, NULL, NULL, 'EstadisticasJugador');
INSERT INTO estadisticas (id, futbolista_id, min_jugados, tar_amarilla, tar_roja, calificacion, goles, asistencias, paradas, porteriasacero, dtype) VALUES (4014, 315, 1100, 2, 0, 6.6, 1, 1, NULL, NULL, 'EstadisticasJugador');
INSERT INTO estadisticas (id, futbolista_id, min_jugados, tar_amarilla, tar_roja, calificacion, goles, asistencias, paradas, porteriasacero, dtype) VALUES (4015, 316, 1250, 3, 0, 6.8, 2, 1, NULL, NULL, 'EstadisticasJugador');
INSERT INTO estadisticas (id, futbolista_id, min_jugados, tar_amarilla, tar_roja, calificacion, goles, asistencias, paradas, porteriasacero, dtype) VALUES (4016, 317, 2200, 6, 0, 7.2, 5, 6, NULL, NULL, 'EstadisticasJugador');
INSERT INTO estadisticas (id, futbolista_id, min_jugados, tar_amarilla, tar_roja, calificacion, goles, asistencias, paradas, porteriasacero, dtype) VALUES (4017, 318, 2000, 4, 0, 7.0, 3, 4, NULL, NULL, 'EstadisticasJugador');
INSERT INTO estadisticas (id, futbolista_id, min_jugados, tar_amarilla, tar_roja, calificacion, goles, asistencias, paradas, porteriasacero, dtype) VALUES (4018, 319, 800, 1, 0, 6.5, 0, 1, NULL, NULL, 'EstadisticasJugador');
INSERT INTO estadisticas (id, futbolista_id, min_jugados, tar_amarilla, tar_roja, calificacion, goles, asistencias, paradas, porteriasacero, dtype) VALUES (4019, 320, 900, 2, 0, 6.6, 1, 0, NULL, NULL, 'EstadisticasJugador');
INSERT INTO estadisticas (id, futbolista_id, min_jugados, tar_amarilla, tar_roja, calificacion, goles, asistencias, paradas, porteriasacero, dtype) VALUES (4020, 321, 1000, 3, 0, 6.7, 2, 1, NULL, NULL, 'EstadisticasJugador');
INSERT INTO estadisticas (id, futbolista_id, min_jugados, tar_amarilla, tar_roja, calificacion, goles, asistencias, paradas, porteriasacero, dtype) VALUES (4021, 322, 500, 1, 0, 6.2, 0, 0, NULL, NULL, 'EstadisticasJugador');
INSERT INTO estadisticas (id, futbolista_id, min_jugados, tar_amarilla, tar_roja, calificacion, goles, asistencias, paradas, porteriasacero, dtype) VALUES (4022, 323, 1400, 2, 0, 6.8, 3, 2, NULL, NULL, 'EstadisticasJugador');
INSERT INTO estadisticas (id, futbolista_id, min_jugados, tar_amarilla, tar_roja, calificacion, goles, asistencias, paradas, porteriasacero, dtype) VALUES (4023, 324, 2100, 4, 0, 7.1, 6, 5, NULL, NULL, 'EstadisticasJugador');
INSERT INTO estadisticas (id, futbolista_id, min_jugados, tar_amarilla, tar_roja, calificacion, goles, asistencias, paradas, porteriasacero, dtype) VALUES (4024, 325, 300, 0, 0, 6.1, 0, 0, NULL, NULL, 'EstadisticasJugador');
INSERT INTO estadisticas (id, futbolista_id, min_jugados, tar_amarilla, tar_roja, calificacion, goles, asistencias, paradas, porteriasacero, dtype) VALUES (4025, 326, 150, 0, 0, 6.0, 0, 0, NULL, NULL, 'EstadisticasJugador');
INSERT INTO estadisticas (id, futbolista_id, min_jugados, tar_amarilla, tar_roja, calificacion, goles, asistencias, paradas, porteriasacero, dtype) VALUES (4026, 327, 700, 1, 0, 6.4, 1, 0, NULL, NULL, 'EstadisticasJugador');
INSERT INTO estadisticas (id, futbolista_id, min_jugados, tar_amarilla, tar_roja, calificacion, goles, asistencias, paradas, porteriasacero, dtype) VALUES (4027, 328, 1900, 3, 0, 7.0, 4, 3, NULL, NULL, 'EstadisticasJugador');
INSERT INTO estadisticas (id, futbolista_id, min_jugados, tar_amarilla, tar_roja, calificacion, goles, asistencias, paradas, porteriasacero, dtype) VALUES (4028, 329, 1100, 2, 0, 6.6, 1, 1, NULL, NULL, 'EstadisticasJugador');
INSERT INTO estadisticas (id, futbolista_id, min_jugados, tar_amarilla, tar_roja, calificacion, goles, asistencias, paradas, porteriasacero, dtype) VALUES (4029, 330, 1600, 3, 0, 6.9, 2, 2, NULL, NULL, 'EstadisticasJugador');
INSERT INTO estadisticas (id, futbolista_id, min_jugados, tar_amarilla, tar_roja, calificacion, goles, asistencias, paradas, porteriasacero, dtype) VALUES (4030, 331, 1700, 4, 0, 6.9, 1, 4, NULL, NULL, 'EstadisticasJugador');
INSERT INTO estadisticas (id, futbolista_id, min_jugados, tar_amarilla, tar_roja, calificacion, goles, asistencias, paradas, porteriasacero, dtype) VALUES (4031, 332, 600, 1, 0, 6.3, 0, 0, NULL, NULL, 'EstadisticasJugador');
INSERT INTO estadisticas (id, futbolista_id, min_jugados, tar_amarilla, tar_roja, calificacion, goles, asistencias, paradas, porteriasacero, dtype) VALUES (4032, 333, 900, 2, 0, 6.5, 1, 0, NULL, NULL, 'EstadisticasJugador');
INSERT INTO estadisticas (id, futbolista_id, min_jugados, tar_amarilla, tar_roja, calificacion, goles, asistencias, paradas, porteriasacero, dtype) VALUES (4033, 334, 1300, 3, 0, 6.8, 2, 1, NULL, NULL, 'EstadisticasJugador');
INSERT INTO estadisticas (id, futbolista_id, min_jugados, tar_amarilla, tar_roja, calificacion, goles, asistencias, paradas, porteriasacero, dtype) VALUES (4034, 335, 400, 0, 0, 6.1, 0, 0, NULL, NULL, 'EstadisticasJugador');

